import 'package:get/get.dart';

class AppTranslations extends Translations {
  @override
  Map<String, Map<String, String>> get keys => {
    'en_US': {
      'cancel': 'Cancel',
      'save': 'Save',
      'delete': 'Delete',
      'edit': 'Edit',
      'add': 'Add',
      'success': 'Success',
      'error': 'Error',
      'warning': 'Warning',
      'confirm': 'Confirm',

      'taskify': 'Taskify',
      'menu': 'Menu',
      'notification': 'Notification',
      'settings': 'Settings',
      'online': 'Online',
      'offline': 'Offline',
      'reminder': 'Reminder',
      'add_reminder': 'Add Reminder',
      'remove_reminder': 'Remove Reminder',
      'delete_all': 'Delete All',
      'delete_all_confirm': 'Delete All Tasks?',
      'delete_all_msg':
          'Are you sure you want to delete all tasks for this day?',
      'deleted': 'Deleted',
      'task_removed': 'Task removed',
      'all_tasks_removed': 'All tasks removed.',
      'select_task': 'Select Task',
      'has_reminder': '(Has Reminder)',

      'add_task': 'Add Task',
      'edit_task': 'Edit Task',
      'update_task': 'UPDATE TASK',
      'add_task_btn': 'ADD TASK',
      'enter_task': 'Enter task',
      'activity': 'Activity',
      'pick_time': 'Pick time',
      'time': 'Time',

      'calendar': 'Calendar',
      'weekly': 'Weekly',
      'daily': 'Daily',
      'today': 'Today',
      'good_morning': 'Good Morning, ',
      'good_afternoon': 'Good Afternoon, ',
      'good_evening': 'Good Evening, ',
      'todays_task': "Today's Task",
      'tasks': 'Tasks',
      'everyday_routine': 'Everyday Routine',
      'routine_for': "'s Routine",
      'search': 'Search...',
      'no_result': 'No result found',
      'no_tasks': 'No tasks found!',
      'no_daily_routines': 'No daily routines',
      'no_routine_day': 'No routine for @day', // @day is a placeholder
      'calendar_mode': 'Calendar Mode',
      'no_events': 'No events for this day...',
      'reminder_on': 'Reminder On',
      'expired': 'Expired',
      'no_valid_tasks': 'No valid tasks available for reminders.',

      'update_prompt': 'Choose how you want to update this task?',
      'select_option': 'Select an option to update',
      'weeks_routine': "Week's\nRoutine",
      'days_routine': "Day's\nRoutine",
      'special_reminder': "Special\nReminder",

      'new_daily_task': 'New Daily Task',
      'daily_prompt': 'What do you want to do everyday?',
      'select_time': 'Select Time',
      'please_select_time': 'Please select a time',
      'set_reminder': 'Set Reminder',
      'task_empty_error': 'Task cannot be empty',
      'add_to_schedule': 'Add to Schedule',
      'save_changes': 'Save Changes',
      'clear_schedule': 'Clear Daily Schedule?',
      'clear_schedule_msg':
          'This will remove all daily tasks. This cannot be undone.',
      'daily_routine_title': 'Daily Routine',
      'everyday_plan': 'Everyday Plan',
      'tasks_scheduled': 'tasks scheduled daily',
      'no_daily_yet': 'No daily routines yet.',
      'disable_all': 'Disable All',
      'enable_all': 'Enable All',
      'clear_all': 'Clear All',

      'special_reminders_title': 'Special Reminders',
      'new_special_event': 'New Special Event',
      'edit_event': 'Edit Event',
      'event_name_hint': 'Event Name (e.g. Birthday)',
      'month': 'Month',
      'day': 'Day',
      'month_error': 'Month must be 1-12',
      'day_error': 'Day must be 1-31',
      'set_time_default': 'Set Time (Default: 12:00 AM)',
      'reminder_always_on': 'Reminder is Always On',
      'save_event': 'Save Event',
      'update_event': 'Update Event',
      'upcoming_events': 'Upcoming Events',
      'no_special_events': 'No special events yet.',
      'event_empty_error': 'Event cannot be empty',

      'no_notifications': 'No notifications yet',
      'recent': 'Recent',
      'last_7_days': 'Last 7 days',
      'remove': 'Remove',

      'appearance': 'Appearance',
      'dark_mode': 'Dark Mode',
      'on': 'On',
      'off': 'Off',
      'language': 'Language',
      'account': 'Account',
      'change_name': 'Change Name',
      'change_pass': 'Change Password',
      'logout': 'Log Out',
      'logout_confirm': 'Are you sure you want to log out?',
      'enter_new_name': 'Enter new name',
      'cooldown_active': 'Cooldown Active',
      'wait_minutes': 'Wait @min minutes to change name.',
      'profile_updated': 'Profile picture updated!',
      'name_updated': 'Name updated!',
      'failed_image': 'Failed to save image',

      'old_password': 'Old Password',
      'new_password': 'New Password',
      'confirm_password': 'Confirm Password',
      'save_password': 'Save Password',
      'fill_all_fields': 'Please fill in all fields.',
      'password_length_error': 'New password must be at least 6 characters.',
      'password_match_error': 'Passwords do not match.',
      'password_success': 'Password updated successfully!',

      'Mon': 'Mon',
      'Tue': 'Tue',
      'Wed': 'Wed',
      'Thu': 'Thu',
      'Fri': 'Fri',
      'Sat': 'Sat',
      'Sun': 'Sun',

      'Monday': 'Monday',
      'Tuesday': 'Tuesday',
      'Wednesday': 'Wednesday',
      'Thursday': 'Thursday',
      'Friday': 'Friday',
      'Saturday': 'Saturday',
      'Sunday': 'Sunday',

      'Jan': 'Jan',
      'Feb': 'Feb',
      'Mar': 'Mar',
      'Apr': 'Apr',
      'May': 'May',
      'Jun': 'Jun',
      'Jul': 'Jul',
      'Aug': 'Aug',
      'Sep': 'Sep',
      'Oct': 'Oct',
      'Nov': 'Nov',
      'Dec': 'Dec',
    },
    'km_KH': {
      'cancel': 'បោះបង់',
      'save': 'រក្សាទុក',
      'delete': 'លុប',
      'edit': 'កែប្រែ',
      'add': 'បន្ថែម',
      'success': 'ជោគជ័យ',
      'error': 'កំហុស',
      'warning': 'ការព្រមាន',
      'confirm': 'បញ្ជាក់',

      'taskify': 'Taskify',
      'menu': 'ម៉ឺនុយ',
      'notification': 'ការជូនដំណឹង',
      'settings': 'ការកំណត់',
      'online': 'អនឡាញ',
      'offline': 'កាត់ផ្តាច់',
      'reminder': 'ការរំលឹក',
      'add_reminder': 'ដាក់ការរំលឹក',
      'remove_reminder': 'លុបការរំលឹក',
      'delete_all': 'លុបទាំងអស់',
      'delete_all_confirm': 'លុបភារកិច្ចទាំងអស់?',
      'delete_all_msg': 'តើអ្នកប្រាកដថាចង់លុបភារកិច្ចទាំងអស់សម្រាប់ថ្ងៃនេះទេ?',
      'deleted': 'បានលុប',
      'task_removed': 'ភារកិច្ចត្រូវបានលុប',
      'all_tasks_removed': 'ភារកិច្ចទាំងអស់ត្រូវបានលុប',
      'select_task': 'ជ្រើសរើសភារកិច្ច',
      'has_reminder': '(មានការរំលឹក)',

      'add_task': 'បន្ថែមភារកិច្ច',
      'edit_task': 'កែប្រែភារកិច្ច',
      'update_task': 'កែប្រែ',
      'add_task_btn': 'បន្ថែម',
      'enter_task': 'បញ្ចូលឈ្មោះភារកិច្ច',
      'activity': 'សកម្មភាព',
      'pick_time': 'ជ្រើសរើសម៉ោង',
      'time': 'ម៉ោង',

      'calendar': 'ប្រតិទិន',
      'weekly': 'ប្រចាំសប្តាហ៍',
      'daily': 'ប្រចាំថ្ងៃ',
      'today': 'ថ្ងៃនេះ',
      'good_morning': 'អរុណសួស្តី, ',
      'good_afternoon': 'ទិវាសួស្តី, ',
      'good_evening': 'សាយ័ណ្ហសួស្តី, ',
      'todays_task': "ភារកិច្ចថ្ងៃនេះ",
      'tasks': 'ភារកិច្ច',
      'everyday_routine': 'ទម្លាប់ប្រចាំថ្ងៃ',
      'routine_for': "ទម្លាប់",
      'search': 'ស្វែងរក...',
      'no_result': 'រកមិនឃើញលទ្ធផល',
      'no_tasks': 'រកមិនឃើញភារកិច្ច!',
      'no_daily_routines': 'មិនមានទម្លាប់ប្រចាំថ្ងៃ',
      'no_routine_day': 'មិនមានទម្លាប់សម្រាប់ @day',

      'calendar_mode': 'ប្រតិទិន',
      'no_events': 'មិនមានព្រឹត្តិការណ៍សម្រាប់ថ្ងៃនេះ...',
      'reminder_on': 'ការរំលឹកបើក',
      'expired': 'ផុតកំណត់',
      'no_valid_tasks': 'មិនមានភារកិច្ចត្រឹមត្រូវសម្រាប់ការរំលឹកទេ។',

      'update_prompt': 'តើអ្នកចង់កែប្រែយ៉ាងដូចម្តេច?',
      'select_option': 'ជ្រើសរើសជម្រើសមួយដើម្បីកែប្រែ',
      'weeks_routine': "ទម្លាប់\nសប្តាហ៍",
      'days_routine': "ទម្លាប់\nថ្ងៃ",
      'special_reminder': "ការរំលឹក\nពិសេស",

      'new_daily_task': 'ទម្លាប់ថ្មី',
      'daily_prompt': 'តើអ្នកចង់ធ្វើអ្វីរៀងរាល់ថ្ងៃ?',
      'select_time': 'ជ្រើសរើសម៉ោង',
      'please_select_time': 'សូមជ្រើសរើសម៉ោង',
      'set_reminder': 'ដាក់ការរំលឹក',
      'task_empty_error': 'ភារកិច្ចមិនអាចទទេបានទេ',
      'add_to_schedule': 'បន្ថែមទៅកាលវិភាគ',
      'save_changes': 'រក្សាទុកការផ្លាស់ប្តូរ',
      'clear_schedule': 'សម្អាតកាលវិភាគប្រចាំថ្ងៃ?',
      'clear_schedule_msg':
          'វានឹងលុបភារកិច្ចប្រចាំថ្ងៃទាំងអស់។ មិនអាចត្រឡប់វិញបានទេ។',
      'daily_routine_title': 'ទម្លាប់ប្រចាំថ្ងៃ',
      'everyday_plan': 'ផែនការរាល់ថ្ងៃ',
      'tasks_scheduled': 'ភារកិច្ចបានកំណត់',
      'no_daily_yet': 'មិនទាន់មានទម្លាប់នៅឡើយទេ។',
      'disable_all': 'បិទទាំងអស់',
      'enable_all': 'បើកទាំងអស់',
      'clear_all': 'សម្អាតទាំងអស់',

      'special_reminders_title': 'ការរំលឹកពិសេស',
      'new_special_event': 'ព្រឹត្តិការណ៍ថ្មី',
      'edit_event': 'កែប្រែព្រឹត្តិការណ៍',
      'event_name_hint': 'ឈ្មោះព្រឹត្តិការណ៍ (ឧ. ថ្ងៃកំណើត)',
      'month': 'ខែ',
      'day': 'ថ្ងៃ',
      'month_error': 'ខែត្រូវតែពី ១-១២',
      'day_error': 'ថ្ងៃត្រូវតែពី ១-៣១',
      'set_time_default': 'កំណត់ម៉ោង (លំនាំដើម: 12:00 AM)',
      'reminder_always_on': 'ការរំលឹកគឺតែងតែបើក',
      'save_event': 'រក្សាទុកព្រឹត្តិការណ៍',
      'update_event': 'កែប្រែព្រឹត្តិការណ៍',
      'upcoming_events': 'ព្រឹត្តិការណ៍ខាងមុខ',
      'no_special_events': 'មិនទាន់មានព្រឹត្តិការណ៍ពិសេសនៅឡើយទេ។',
      'event_empty_error': 'ព្រឹត្តិការណ៍មិនអាចទទេបានទេ',

      'no_notifications': 'មិនទាន់មានការជូនដំណឹង',
      'recent': 'ថ្មីៗ',
      'last_7_days': '៧ ថ្ងៃចុងក្រោយ',
      'remove': 'លុបចេញ',

      'appearance': 'រូបរាង',
      'dark_mode': 'មុខងារងងឹត',
      'on': 'បើក',
      'off': 'បិទ',
      'language': 'ភាសា',
      'account': 'គណនី',
      'change_name': 'ប្តូរឈ្មោះ',
      'change_pass': 'ប្តូរពាក្យសម្ងាត់',
      'logout': 'ចាកចេញ',
      'logout_confirm': 'តើអ្នកប្រាកដថាចង់ចាកចេញឬ?',
      'enter_new_name': 'បញ្ចូលឈ្មោះថ្មី',
      'cooldown_active': 'រង់ចាំបន្តិច',
      'wait_minutes': 'រង់ចាំ @min នាទីដើម្បីប្តូរឈ្មោះ។',
      'profile_updated': 'បានធ្វើបច្ចុប្បន្នភាពរូបភាព!',
      'name_updated': 'បានធ្វើបច្ចុប្បន្នភាពឈ្មោះ!',
      'failed_image': 'បរាជ័យក្នុងការរក្សាទុករូបភាព',

      'old_password': 'ពាក្យសម្ងាត់ចាស់',
      'new_password': 'ពាក្យសម្ងាត់ថ្មី',
      'confirm_password': 'បញ្ជាក់ពាក្យសម្ងាត់',
      'save_password': 'រក្សាទុកពាក្យសម្ងាត់',
      'fill_all_fields': 'សូមបំពេញគ្រប់ចន្លោះ។',
      'password_length_error': 'ពាក្យសម្ងាត់ថ្មីត្រូវតែមានយ៉ាងតិច ៦ តួ។',
      'password_match_error': 'ពាក្យសម្ងាត់មិនត្រូវគ្នាទេ។',
      'password_success': 'បានធ្វើបច្ចុប្បន្នភាពពាក្យសម្ងាត់!',

      'Mon': 'ច័ន្ទ',
      'Tue': 'អង្គារ',
      'Wed': 'ពុធ',
      'Thu': 'ព្រហ',
      'Fri': 'សុក្រ',
      'Sat': 'សៅរ៍',
      'Sun': 'អាទិត្យ',

      'Monday': 'ថ្ងៃច័ន្ទ',
      'Tuesday': 'ថ្ងៃអង្គារ',
      'Wednesday': 'ថ្ងៃពុធ',
      'Thursday': 'ថ្ងៃព្រហស្បតិ៍',
      'Friday': 'ថ្ងៃសុក្រ',
      'Saturday': 'ថ្ងៃសៅរ៍',
      'Sunday': 'ថ្ងៃអាទិត្យ',

      'Jan': 'មករា',
      'Feb': 'កុម្ភៈ',
      'Mar': 'មីនា',
      'Apr': 'មេសា',
      'May': 'ឧសភា',
      'Jun': 'មិថុនា',
      'Jul': 'កក្កដា',
      'Aug': 'សីហា',
      'Sep': 'កញ្ញា',
      'Oct': 'តុលា',
      'Nov': 'វិច្ឆិកា',
      'Dec': 'ធ្នូ',
    },
  };
}
